### ISSUE TITLE
Produces strict mode error

### ISSUE THREAD

**Issue by hollowdoor** [bahamas10/node-clear#5]
When `"use strict";` is in a script, or function above `node-clear` this error appears:

```
SyntaxError: Octal literal in strict mode
```

This will also break es2015 modules.

**Comment by Introvertuous** [comment]
I am not a huge fan of one liner npm pacakges.
Use this: ```process.stdout.write('\x1Bc');```
Or make a PR, your choice.

**Comment by hollowdoor** [comment]
That is what I use. There is actually a better way to do it. For running anywhere.

```javascript
module.exports = typeof process === 'object'
&& typeof process.stdout === 'object' && typeof (process.stdout.write) === 'function'
? ()=>process.stdout.write('\x1Bc')
: typeof window !== 'undefined' && typeof (console.clear) === 'function'
? ()=>console.clear()
: ()=>'uh oh!';
```

I'm not a fan of one liner modules either. Though I'm not a fan of multi-line modules as well. I mostly just like modules. :smile:

**Comment by hollowdoor** [comment]
There's already a pull request for the strict mode error.

https://github.com/bahamas10/node-clear/pull/7

**Comment by bahamas10** [comment]
thanks everyone, sorry i didn't see these issue sooner.

```
$ npm publish
+ clear@0.1.0
```

Should fix this issue!

(https://github.com/bahamas10/node-clear/commit/c8fcf07a87574b345fc9f7a1a42629afeccb826d)
